site_name: 重庆大学2019级硬件综合设计实验文档
copyright: 'Copyright &copy; 2021 College of Computer Science, Chongqing University.'
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - 主页: index.md
  - 环境配置:
    - Vivado安装: env/vivado.md
    - 实验资料包: env/resource.md
  - 基本任务:
    - 回顾计组实验四: basic/lab4.md
    - 扩展到52条指令: basic/extend_52.md
    - 扩展到57条指令: basic/extend_57.md
    - 基础Cache:      basic/basic_cache.md
  - 扩展实验:
    - AXI接口: ext/axi.md
    - 性能优化: ext/opt.md
    - Cache: ext/cache.md
    - MMU: ext/mmu.md
    - 运行操作系统: ext/os.md
    - LoongArch32: ext/la32.md
  - 调试技巧:
    - 使用波形图: tips/wave_debug.md