site_name: 重庆大学2019级硬件综合设计实验文档
copyright: 'Copyright &copy; 2021 College of Computer Science, Chongqing University.'
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - 主页: index.md
  - 环境配置: env.md
  - 基本任务: basic.md
  - 扩展实验: ext.md
  - 调试期缴: tips.md