site_name: 重庆大学硬件综合设计实验文档
copyright: 'Copyright &copy; 2022 College of Computer Science, Chongqing University.'
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: material/memory
nav:
  - 主页: index.md
  - 环境配置:
    - 工具: env/tools.md
    - 实验资料包: env/resource.md
  - 基本任务:
    - 了解语言: basic/language.md
    - 回顾计组实验四: basic/lab4.md
    - 扩展到52条指令: basic/extend_52.md
    - 扩展到57条指令: basic/extend_57.md
    - 封装SRAM-SOC:      basic/sram_soc.md
    - 基础Cache:      basic/basic_cache.md
    - 多周期操作的握手信号: basic/handshake.md
  - 扩展实验:
    - AXI接口: ext/axi.md
    - 性能优化: ext/opt.md
    - Cache: ext/cache.md
    - MMU: ext/mmu.md
    - 运行操作系统: ext/os.md
    - LoongArch32: ext/la32.md
  - 调试技巧:
    - 常见问题: tips/common.md
    - 使用波形图: tips/wave_debug.md
    - Git使用: tips/git.md
    - 反汇编: tips/disasm.md
    - Windows原生GTKWave: tips/win-gtkwave.md
  - RISC-V挑战组:
    - RISC-V指令集: rv/intro.md
    - RISC-V基础整数指令集: rv/rv64i.md
    - RISC-V整数乘除法扩展: rv/rv64m.md
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_name: 'CO-lab-docs-CQU'
repo_url: 'https://github.com/CQU-CS-LABs/CO-lab-docs-CQU'